### ISSUE TITLE
Crash when adding/editing review without tapping on "Edit Tags"

### ISSUE THREAD

**Issue by LECAGO** [Alcidauk/CineLog#70]
If I try to add or edit a review without tapping the "Edit Tags" button, the app crashes with the following error:

````
type: crash
osVersion: google/panther/panther:13/TQ3A.230901.001/2023091800:user/release-keys
package: com.ulicae.cinelog:38
process: com.ulicae.cinelog
processUptime: 6667 + 227 ms
installer: com.android.packageinstaller

java.lang.NullPointerException: Attempt to read from field 'boolean[] com.ulicae.cinelog.android.v2.fragments.review.edit.TagChooserDialog.selectedTags' on a null object reference in method 'void com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.updateTags()'
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.updateTags(ReviewEditionFragment.java:238)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.onFabClick(ReviewEditionFragment.java:232)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.lambda$onViewCreated$0$com-ulicae-cinelog-android-v2-fragments-review-edit-ReviewEditionFragment(ReviewEditionFragment.java:80)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

````

App version: 2.0.0-beta3 from F-Droid
OS: GrapheneOS Android 13

**Comment by KjmT6459** [comment]
Same here
App version: 2.0.0-beta3 from F-Droid
OS: GrapheneOS Android 14
Device: Pixel 5
```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023101300:user/release-keys
package: com.ulicae.cinelog:38
process: com.ulicae.cinelog
processUptime: 26603 + 953 ms
installer: com.machiav3lli.fdroid

java.lang.NullPointerException: Attempt to read from field 'boolean[] com.ulicae.cinelog.android.v2.fragments.review.edit.TagChooserDialog.selectedTags' on a null object reference in method 'void com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.updateTags()'
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.updateTags(ReviewEditionFragment.java:238)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.onFabClick(ReviewEditionFragment.java:232)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.lambda$onViewCreated$0$com-ulicae-cinelog-android-v2-fragments-review-edit-ReviewEditionFragment(ReviewEditionFragment.java:80)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by fabmazz** [comment]
Can confirm on Android 14, Galaxy A52s. Same behaviour, only by touching on the tags button a crash is avoided.
