### ISSUE TITLE
Sorting by viewing date crashes app.

### ISSUE THREAD

**Issue by UKFilmNerd** [Alcidauk/CineLog#74]
If I sort my films by viewing date, the words "Unknown release year" appears at the top of the list. Touching those words makes the app crash.

**Comment by UKFilmNerd** [comment]
My bad. I just realised none of my entries had viewing dates. The "sort by viewing date" works properly now, but touching the year causes the app to quit instantly. I managed to grab this error message.

java.lang.ClassCastException: java.lang.String cannot be cast to com.ulicae.cinelog.data.dto.KinoDto
	at com.ulicae.cinelog.android.v2.fragments.review.list.ReviewListFragment.lambda$applyListeners$4$com-ulicae-cinelog-android-v2-fragments-review-list-ReviewListFragment(ReviewListFragment.java:139)
	at com.ulicae.cinelog.android.v2.fragments.review.list.ReviewListFragment$$ExternalSyntheticLambda3.onItemClick(Unknown Source:6)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1221)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3214)
	at android.widget.AbsListView$3.run(AbsListView.java:4228)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

I hope this app is till being developed, Just fix this and the Edit Tags issue to stop the crashes, and it suits my needs perfectly.

**Comment by Alcidauk** [comment]
Hi UKFilmNerd,

Yes, the app is still being developed, I did not find time these last months. 

I hope I will fix your issue in the next few weeks.

Stay tuned !

**Comment by Alcidauk** [comment]
Hi,

Just fixed it, it should be available in the next release.

Pierre
