### ISSUE TITLE
App crashes when trying to add movies/series without tag.

### ISSUE THREAD

**Issue by WirelessAlien** [Alcidauk/CineLog#75]
Log- 

> FATAL EXCEPTION: main
Process: com.ulicae.cinelog, PID: 11801
java.lang.NullPointerException: Attempt to read from field 'boolean[] com.ulicae.cinelog.android.v2.fragments.review.edit.TagChooserDialog.selectedTags' on a null object reference
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.updateTags(ReviewEditionFragment.java:238)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.onFabClick(ReviewEditionFragment.java:232)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment.lambda$onViewCreated$0$com-ulicae-cinelog-android-v2-fragments-review-edit-ReviewEditionFragment(ReviewEditionFragment.java:80)
	at com.ulicae.cinelog.android.v2.fragments.review.edit.ReviewEditionFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7566)
	at android.view.View.performClickInternal(View.java:7539)
	at android.view.View.access$3600(View.java:831)
	at android.view.View$PerformClick.run(View.java:28886)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7912)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by Alcidauk** [comment]
Hi,

thank you for your report. The bug is however the same that https://github.com/Alcidauk/CineLog/issues/70.

Let me know when you use the last version (which will be built soon) if you have got the same issue.

Pierre
